# Generated by Django 3.0.6 on 2020-05-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', 'create_data_sources'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasource',
            options={'ordering': ('-last_use_time',), 'verbose_name': 'Источник', 'verbose_name_plural': 'Источники'},
        ),
        migrations.AlterField(
            model_name='datasource',
            name='plugin',
            field=models.CharField(choices=[('aggregator.plugins.MoiKrugPlugin', 'Мой Круг'), ('aggregator.plugins.RemoteJobPlugin', 'Remote Job'), ('aggregator.plugins.VKPlugin', 'Вконтакте'), ('aggregator.plugins.RssPlugin', 'RssPlugin')], max_length=250),
        ),
    ]
