# Generated by Django 3.0.5 on 2020-05-05 17:29

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0012_periodictask_expire_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='datasource_icons/', validators=[django.core.validators.validate_image_file_extension], verbose_name='Иконка')),
                ('icon_url', models.URLField(blank=True, null=True, verbose_name='Иконка из интернета')),
                ('plugin', models.CharField(choices=[('aggregator.plugins.MoiKrugPlugin', 'Мой Круг'), ('aggregator.plugins.RemoteJobPlugin', 'Remote Job'), ('aggregator.plugins.VKPlugin', 'Вконтакте')], max_length=250)),
                ('configuration', django.contrib.postgres.fields.jsonb.JSONField()),
                ('last_use_time', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.PeriodicTask')),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
                'ordering': ('last_use_time',),
            },
        ),
    ]
