# Generated by Django 3.1.2 on 2020-12-19 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0004_sourceconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='source_configuration',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='aggregator.sourceconfiguration'),
        ),
    ]
