# Generated by Django 3.1.2 on 2020-12-19 14:37

from django.db import migrations


def forwards_func(apps, schema_editor):
    SourceConfiguration = apps.get_model('aggregator', 'SourceConfiguration')
    DataSource = apps.get_model('aggregator', 'DataSource')
    db_alias = schema_editor.connection.alias
    sources = DataSource.objects.using(db_alias).all()
    for source in sources.iterator():
        source_configuration = SourceConfiguration()
        source_configuration.url = source.configuration.get('url', '')
        source_configuration.keywords = source.configuration.get('keywords', list())
        source_configuration.stop_words = source.configuration.get('stop_words', list())
        time_format = source.configuration.get('pub_date_format') or source.configuration.get('time_format') or ''

        source_configuration.time_format = time_format
        source_configuration.datasource = source
        source_configuration.save()

        source.source_configuration = source_configuration
        source.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('aggregator', '0005_datasource_source_configuration'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
