# Generated by Django 3.1.2 on 2020-12-21 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0006_auto_20201219_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='configuration',
        ),
    ]
