# Generated by Django 3.1.2 on 2020-12-21 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0007_remove_datasource_configuration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasource',
            old_name='source_configuration',
            new_name='configuration',
        ),
    ]
