# Generated by Django 3.0.5 on 2020-05-05 16:33
import json
import os

from django.conf import settings
from django.db import migrations
from django_celery_beat.models import MINUTES


def forwards_func(apps, schema_editor):
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')
    DataSource = apps.get_model('aggregator', 'DataSource')
    IntervalSchedule = apps.get_model('django_celery_beat', 'IntervalSchedule')

    fixture = os.path.join(settings.BASE_DIR, 'aggregator', 'fixtures', 'datasources.json')
    with open(fixture) as f:
        data = json.load(f)
        for source in data:
            schedule, _ = IntervalSchedule.objects.get_or_create(
                every=20,
                period=MINUTES
            )
            ds = DataSource.objects.create(
                title=source['fields']['title'],
                plugin=source['fields']['python_class'],
                configuration=source['fields']['configuration'],
                icon=source['fields']['image'],
            )
            ds.task = PeriodicTask.objects.create(
                interval=schedule,
                name=ds.title,
                task='aggregator.tasks.aggregate_content',
                kwargs=json.dumps({
                    'datasource_id': ds.id
                })
            )
            ds.save()


def backwards_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('aggregator', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func)
    ]
