# Generated by Django 3.0.6 on 2020-05-06 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image_url',
            new_name='icon_url',
        ),
    ]
