# Generated by Django 3.0.6 on 2020-05-06 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0001_auto_20200506_1544'),
        ('articles', '0004_remove_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='aggregator.DataSource'),
        ),
    ]
