# Generated by Django 3.1.2 on 2020-10-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200506_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
