# Generated by Django 3.1.2 on 2020-12-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20201020_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='icon_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
