# Generated by Django 3.1.7 on 2021-03-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20201226_1939'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['id'], name='articles_ar_id_a6002d_idx'),
        ),
    ]
