# Generated by Django 3.1.7 on 2021-03-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20210307_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='hash',
            field=models.CharField(editable=False, max_length=40, unique=True),
        ),
    ]
