# Generated by Django 3.0.5 on 2020-04-28 10:16
import os

from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.db import migrations


def forwards_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    User = apps.get_model(settings.AUTH_USER_MODEL)
    password = os.environ.get('ADMIN_PASSWORD')
    user = User.objects.using(db_alias).create(
        username='superuser',
        first_name='Mikhail',
        last_name='Pavlov',
        is_staff=True,
        is_superuser=True,
        password=make_password('123')
    )
    user.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
